apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
- serviceAccount.yaml
#- github.com/prometheus-operator/kube-prometheus?ref=v0.10.0
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0alertmanagerCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0podmonitorCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0probeCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0prometheusCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0prometheusruleCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0servicemonitorCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/0thanosrulerCustomResourceDefinition.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/setup/namespace.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-alertmanager.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-podDisruptionBudget.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-secret.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/alertmanager-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-configuration.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-deployment.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/blackboxExporter-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-config.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-dashboardDatasources.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-dashboardDefinitions.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-dashboardSources.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-deployment.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/grafana-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubePrometheus-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-deployment.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubeStateMetrics-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-serviceMonitorApiserver.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/kubernetesControlPlane-serviceMonitorKubelet.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-daemonset.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/nodeExporter-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-podDisruptionBudget.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-prometheus.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-roleBindingConfig.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-roleBindingSpecificNamespaces.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-roleConfig.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-roleSpecificNamespaces.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheus-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-apiService.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-clusterRoleAggregatedMetricsReader.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-clusterRoleBindingDelegator.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-clusterRoleServerResources.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-configMap.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-deployment.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-podDisruptionBudget.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-roleBindingAuthReader.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusAdapter-serviceMonitor.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-clusterRole.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-clusterRoleBinding.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-deployment.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-networkPolicy.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-prometheusRule.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-service.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheusmanifests/prometheusOperator-serviceMonitor.yaml
- serviceMonitor.yaml
#- github.com/codefresh-io/cli-v2/manifests/argo-workflows?ref=v0.0.301