apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  labels:
    app: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    name: in-cluster
  project: default
  source:
    path: ./kustomize/prometheus/overlays/dev
    repoURL: https://github.com/jcantosz/helm-duo.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: true
